#ifndef BALL_ISA_H
#define BALL_ISA_H

#define BB_FUNC7_TRANSPOSE 49
#define BB_FUNC7_SMATMUL_OS 65
#define BB_FUNC7_SMATMUL_WS 68
#define BB_FUNC7_IM2COL 48
#define BB_FUNC7_FP2INT 51
#define BB_FUNC7_INT2FP_TENSOR 52
#define BB_FUNC7_INT2FP_CHANNEL 54
#define BB_FUNC7_RELU 50
#define BB_FUNC7_MATADD 64

#endif
