version: 2

# update weekly (to avoid spam)
updates:
  # submit a PR for bumping GH-A dependencies
  - package-ecosystem: github-actions
    schedule:
      interval: "weekly"
    directory: /
    labels:
      - "dependencies"
      - "changelog:omit"
